/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import InstructionSet.Instruction;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 * A classe <b>CodeMemory</b> é, atualmente, a classe principal do simulador. É nela que estão os principais objetos do programa.
     * Ela também contém a tabela do código de máquina em hexadecimal e a tabela das intruções e seus mnemônicos na memória de código.
 * @author Gerson Menezes e Vinícius Santos
 * @version 1.0
 */
public class CodeMemory extends javax.swing.JFrame {
    
    /**
     * O objeto <b>cpu</b> é uma instância da classe <b>Cpu</b>.
     */
    public static Cpu cpu = new Cpu();
    /**
     * O objeto <b>memory</b> é uma instância da classe <b>Memory</b>.
     */
    public static Memory memory = cpu.memory;
    /**
     * O objeto <b>ram</b> é uma instância da classe <b>Ram</b>.
     */
    Ram ram = new Ram();
    
    /**
     * O método <b>CodeMemory</b> é o construtor padrão da classe CodeMemory.
     */
    public CodeMemory() {
        initComponents();
        DefaultTableCellRenderer rightRender = new DefaultTableCellRenderer();
        rightRender.setHorizontalAlignment(JLabel.CENTER);
        
        for(int i = 0; i < hexTable.getColumnCount(); i++)
            hexTable.getColumnModel().getColumn(i).setCellRenderer(rightRender);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        hexTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mneTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        execBtn = new javax.swing.JButton();
        openRam = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(736, 455));

        hexTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hexTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "0A", "0B", "0C", "0D", "0E", "0F"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        hexTable.setColumnSelectionAllowed(true);
        hexTable.setRowHeight(26);
        hexTable.setShowGrid(true);
        hexTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(hexTable);
        hexTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (hexTable.getColumnModel().getColumnCount() > 0) {
            hexTable.getColumnModel().getColumn(0).setResizable(false);
            hexTable.getColumnModel().getColumn(1).setResizable(false);
            hexTable.getColumnModel().getColumn(2).setResizable(false);
            hexTable.getColumnModel().getColumn(3).setResizable(false);
            hexTable.getColumnModel().getColumn(4).setResizable(false);
            hexTable.getColumnModel().getColumn(5).setResizable(false);
            hexTable.getColumnModel().getColumn(6).setResizable(false);
            hexTable.getColumnModel().getColumn(7).setResizable(false);
            hexTable.getColumnModel().getColumn(8).setResizable(false);
            hexTable.getColumnModel().getColumn(9).setResizable(false);
            hexTable.getColumnModel().getColumn(10).setResizable(false);
            hexTable.getColumnModel().getColumn(11).setResizable(false);
            hexTable.getColumnModel().getColumn(12).setResizable(false);
            hexTable.getColumnModel().getColumn(13).setResizable(false);
            hexTable.getColumnModel().getColumn(14).setResizable(false);
            hexTable.getColumnModel().getColumn(15).setResizable(false);
        }

        jLabel1.setText("Instructions");

        jLabel2.setText("HEX");

        mneTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Adress", "Mnemonic", "Opcode"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mneTable.setRowHeight(26);
        mneTable.setShowGrid(true);
        mneTable.getTableHeader().setReorderingAllowed(false);
        mneTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mneTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(mneTable);
        if (mneTable.getColumnModel().getColumnCount() > 0) {
            mneTable.getColumnModel().getColumn(0).setResizable(false);
            mneTable.getColumnModel().getColumn(0).setPreferredWidth(60);
            mneTable.getColumnModel().getColumn(1).setResizable(false);
            mneTable.getColumnModel().getColumn(2).setResizable(false);
            mneTable.getColumnModel().getColumn(2).setPreferredWidth(40);
        }

        jButton1.setText("Load HEX code");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        execBtn.setText("Execute");
        execBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                execBtnActionPerformed(evt);
            }
        });

        openRam.setText("Open RAM");
        openRam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openRamActionPerformed(evt);
            }
        });

        jButton2.setText("STEP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(execBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(openRam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(openRam)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(execBtn)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * <b>jButton1ActionPerformed</b> é o método chamado ao clicar nao botão <b>Load HEX code<\b>.
     *
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Charge cg = new Charge();
        cg.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * <b>execBtnActionPerformed</b> é o método chamado ao clicar no botão Execute, simplesmenta chama o método <b>exec<\b> do objeto <b>cpu</b> 
     * 
     */
    private void execBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_execBtnActionPerformed
        if (cpu.memory != null){
            cpu.exec();
        }
    }//GEN-LAST:event_execBtnActionPerformed
    /**
     * O método <b>mneTableMouseClicked</b> recebe o input de clique na tabela dos mnemônicos a fim de mostrar sua respectiva localização no código de máquina.
     * 
     */
    private void mneTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mneTableMouseClicked
        int line = mneTable.rowAtPoint(evt.getPoint());
        DefaultTableModel model = (DefaultTableModel) mneTable.getModel();
        String stAdress = (String) model.getValueAt(line, 0);
        //System.out.println(stAdress);
        if(stAdress != null){
            int adress = Integer.parseInt(stAdress, 16);
            hexTable.changeSelection(adress/16, adress%16, false, false);
        }
    }//GEN-LAST:event_mneTableMouseClicked
    
    /**
     * <b>openRamActionPerformed</b> é executado quando o botão <b>Open RAM</b> é clicado e deixa visível a memória ram do microcontrolador
     *
     */
    private void openRamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openRamActionPerformed
        ram.setVisible(true);
    }//GEN-LAST:event_openRamActionPerformed
    
    /**
     * <b>jButton2ActionPerformed</b> é executado quando o botão <b>STEP</b> é clicado e chama o método <b>step</b> do objeto <b>cpu</b>
     * 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Cpu.step();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * <b>loadHexTable</b> é o método responsável por carregar a tabela do código hexadecimal
     * @param data é as informações que provém do código carregado na classe <b>Charge</b>
     */
    static void loadHexTable(int[] data){        
        DefaultTableModel model = (DefaultTableModel) hexTable.getModel();
        int column = 0;
        Object[] row = new Object[model.getColumnCount()];
        for(Integer i : data){
            row[column] = String.format("%02x", i).toUpperCase();
            column++;
            if (column > model.getColumnCount() - 1 || model.getColumnCount() * model.getRowCount() + column == data.length){
                column = 0;
                model.addRow(row);
                row = new Object[model.getColumnCount()];
            }
        }
    }
    
    /**
     * <b>loadMnemonicTable</b> é o método responsável por carregar a tabela de instruções e seus mnemônicos
     * @param inst é as instruções provenientes do código carregado na classe <b>Charge</b>
     */
    static void loadMnemonicTable(Instruction[] inst){
        DefaultTableModel model = (DefaultTableModel) mneTable.getModel();
        for(int i = 0; i < inst.length; i++){
            // falta setar o endereço, corno
            Object[] row = new Object[model.getColumnCount()];
            row[0] = String.format("%04x", i).toUpperCase();
            if(inst[i] == null) {
                //ESTA LINHA O_O
                //model.addRow(row);
                continue;
            }
            
            String operands = " ";
            if(inst[i].args.length > 0){
                for(int j: inst[i].args){
                    operands += Integer.toHexString(j).toUpperCase() + ", ";
                }
                operands = operands.substring(0, operands.length() - 2);
            }
            row[1] = inst[i].mnemonic + operands;
            
            if(inst[i].opCode >= 0x78 && inst[i].opCode <= 0x7f){
                //MOV R0 - R7
                row[1] = inst[i].mnemonic + " R" + (inst[i].opCode - 0x78)+"," + operands;
                
            }else if(inst[i].opCode >= 0xE5 && inst[i].opCode <= 0xEF || inst[i].opCode == 0x74){
                // MOV A
                if(inst[i].opCode >= 0xE8)
                    //MOV A R0-R7
                    operands = " R" + (inst[i].opCode - 0xE8);
                row[1] = inst[i].mnemonic + " A," + operands;
                
            }else if(inst[i].opCode == 0xA2){
                //MOV C
                row[1] = inst[i].mnemonic + " C," + operands;
                
            }else if(inst[i].opCode >= 0x94 && inst[i].opCode <= 0x9F){
                //SUBB
                if(inst[i].opCode >= 0x98){
                    operands = " R" + (inst[i].opCode - 0x98);
                }else if(inst[i].opCode == 0x96)
                    operands = " @R0";
                else if(inst[i].opCode == 0x97)
                    operands = " @R1";
                row[1] = inst[i].mnemonic + " A," + operands;
                
            }
            row[2] = Integer.toHexString(inst[i].opCode).toUpperCase();
            model.addRow(row);
        }
        color(0);
    }
    
    /**
     * <b>color</b> é o método para colorir determinado endereço da tabela dos mnemônicos
     * @param address é o endereço da instrução na memória desejado
     */
    public static void color(int address){
        mneTable.setDefaultRenderer(Object.class, new DefaultTableCellRenderer(){

            @Override
            public Component getTableCellRendererComponent(JTable table, Object Value,
                    boolean isSelected, boolean hasFocus, int row, int column){
                
                JLabel label = (JLabel) super.getTableCellRendererComponent(table, Value,
                        isSelected, hasFocus, row, column);
                //*************************************************************
                Color c = new Color(0,0,0,0);
                if (table.getValueAt(row, 0).equals(String.format("%04x", address).toUpperCase())){
                    c = new Color(180,0,0);
                }
                label.setBackground(c);
                //*************************************************************
                return label;
            }
        });
        mneTable.repaint();
    }
    
    /**
     * O método <b>reset</b> reseta a tabela do código de máquina e das instruções e seus mnemônicos
     */
    public static void reset(){
        DefaultTableModel model_mneTable = (DefaultTableModel) mneTable.getModel();
        for (int row = mneTable.getRowCount()-1; row >= 0; row--){
            model_mneTable.removeRow(row);
        }

        DefaultTableModel model_hexTable = (DefaultTableModel) hexTable.getModel();
        for (int row = hexTable.getRowCount()-1; row >= 0; row--){
            model_hexTable.removeRow(row);
        }
    }
    
//    public static void colorir(int address){
//        System.out.println("Colorindo");
//        color(address);
//    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            javax.swing.UIManager.setLookAndFeel( new FlatDarkLaf() );
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
            ex.printStackTrace();
            
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CodeMemory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton execBtn;
    public static javax.swing.JTable hexTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable mneTable;
    private javax.swing.JButton openRam;
    // End of variables declaration//GEN-END:variables
}
